apiVersion: v1
kind: Service
metadata:
  name: public-svc
  labels:
    app: realestate-projectapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: realestate-projectapi
